#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := led_strip

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/led_strip
EXTRA_COMPONENT_DIRS += $(IDF_PATH)/examples/common_components/pulse_width_encoding

include $(IDF_PATH)/make/project.mk
