#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := dshot_esc_ctl

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/pulse_width_encoding

include $(IDF_PATH)/make/project.mk
